jobs:
  cpu_attack:
    image: docker.io/luckysideburn/kubeinvaders-stress-ng:latest
    command: "stress-ng"
    args:
      - "--cpu"
      - "4"
      - "--io"
      - "2"
      - "--vm"
      - "1"
      - "--vm-bytes"
      - "1G"
      - "--timeout"
      - "10s"
      - "--metrics-brief"

  mem_attack:
    image: docker.io/luckysideburn/kubeinvaders-stress-ng:latest
    command: "stress-ng"
    args: 
      - "--vm 2"
      - "-–vm-bytes"
      - "1G"

experiments:
  - name: cpu_attack_exp
    job: cpu_attack
    loop: 5
    after:
      check_url: https://google.it
      check_payload: ''
      check_tls_ignore: true
  - name: mem_attack_exp
    job: mem_attack
    loop: 5
    after:
      check_url: https://google.it
      check_payload: ''
      check_tls_ignore: true