name: Docker Image CI

on:
  push:
    branches: [ "master", "feat/pipeline-improvement" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_TAG: ${{ github.event.action == "push" && 'latest' || 'latest-pull-request' }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.REGISTRY_ROBOT_USERNAME }}
        password: ${{ secrets.REGISTRY_ROBOT_PASSWORD }}

    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ vars.REGISTRY_ADDRESS }}/${{ vars.REGISTRY_USERNAME }}/kubeinvaders:${{ env.IMAGE_TAG }}
        docker push ${{ vars.REGISTRY_ADDRESS }}/${{ vars.REGISTRY_USERNAME }}/kubeinvaders:${{ env.IMAGE_TAG }}

    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      with:
        driver: docker
        kubernetes-version: v1.26.3
        cpus: 4
        memory: 2048m

    - name: Try the cluster!
      run: kubectl get pods -A

    - name: Deploy example
      run: |
        kubectl apply -f minikube-setup/manifests --wait=true
        kubectl get all -n "ns-1"

    - name: Deploy with helm
      run: |
        helm upgrade --install \
          kubeinvaders \
          -n kubeinvaders \
          --create-namespace \
          helm-charts/kubeinvaders \
          --set ingress.enabled=true \
          --set deployment.image.tag=latest \
          --set ingress.hostName=kubeinvaders.local \
          --set-string config.target_namespace="ns-1" \
          --set deployment.image.repository=${{ vars.REGISTRY_ADDRESS }}/${{ vars.REGISTRY_USERNAME }}

    - name: Check if service is available
      run: |
        kubectl get all -n kubeinvaders


