name: Docker Image CI

on:
  push:
    branches: [ "master", "feat/pipeline-improvement" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Quay.io
      uses: docker/login-action@v2
      if: github.repository_owner == 'Greendor1234'
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ROBOT_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag quay.io/abitocchi/kubeinvaders:latest
        docker push quay.io/abitocchi/kubeinvaders:latest

    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      with:
        driver: docker
        kubernetes-version: v1.26.3
        cpus: 4
        memory: 2048m

    - name: Try the cluster!
      run: kubectl get pods -A

    - name: Deploy example
      run: kubectl apply -f minikube-setup/manifests

    - name: Deploy with helm
      run: |
        helm upgrade --install kubeinvaders \
          --set-string config.target_namespace="ns-1" \
          -n kubeinvaders \
          helm-charts/kubeinvaders \
          --set ingress.enabled=true \
          --set ingress.hostName=kubeinvaders.local \
          --set deployment.image.tag=$(image_tag)


